server:
  port: 5555
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url: 
      defautlzone: http://localhost:8761/eureka/
      
  instance:
    hostname: localhost

spring:
  application:
    name: zuul
    
management:
  endpoints:
    web:
      exposure:
        include:
        - "routes"    
